name: logs # name of the experiment needed for the logs

faults:
  dir: ./faults # path needed for the fault campaing

config:
  format: float16

gpu:
  sm: 4
  cluster: 2
  CTAs_buffer: 2

scheduler: 'GlobalRoundRobin'


mxm:
  MS: 16 # for now, this value is constant
  NS: 16 # for now, this value is constant
  KS: 16 # for now, this value is constant
