name: logs # name of the experiment needed for the logs

faults:
  dir: ./PyOpenTCU/faults # path needed for the fault campaing
  exaustive_test: 86015
  faults_to_inject : 8629 #this statistic fault injection will produce results with 1% error margin and 95% confidentiality

config:
  format: float16

gpu:
  sm: 4
  cluster: 2
  CTAs_buffer: 2

scheduler: 'GlobalRoundRobin'

mxm:
  MS: 16 # for now, this value is constant
  NS: 16 # for now, this value is constant
  KS: 16 # for now, this value is constant

workers: 32